name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Deploy
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_NAME: ${{ secrets.HF_NAME }}
        HF_SPACES: ${{ secrets.HF_SPACES }}
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name "Bot"

        git clone https://huggingface.co/spaces/$HF_NAME/$HF_SPACES hf

        cp main.py hf/
        cp pyproject.toml hf/
        cp uv.lock hf/
        cp Dockerfile hf/

        cd hf
        git add .
        git commit -m "Deploy" || echo "No changes"
        git push https://$HF_NAME:$HF_TOKEN@huggingface.co/spaces/$HF_NAME/$HF_SPACES main